# Generated by Django 4.2.4 on 2024-05-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0004_alter_usuarioempresa_inversionactual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioempresa',
            name='acciones',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
