# Generated by Django 4.2.4 on 2024-05-05 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0005_usuarioempresa_acciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioegresos',
            name='fecha',
            field=models.DateField(auto_now_add=True, default="2024-04-05"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UsuarioIngresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresado', to='UserData.usuario')),
            ],
        ),
    ]
