# Generated by Django 4.2.4 on 2024-05-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0006_usuarioegresos_fecha_usuarioingresos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioegresos',
            name='fecha',
        ),
    ]
