# Generated by Django 4.2.4 on 2024-05-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0007_remove_usuarioegresos_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioingresos',
            name='fecha',
        ),
    ]
