# Generated by Django 4.2.4 on 2024-05-05 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0008_remove_usuarioingresos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioegresos',
            name='fecha',
            field=models.DateField(default=datetime.date(2024, 5, 4)),
        ),
        migrations.AddField(
            model_name='usuarioingresos',
            name='fecha',
            field=models.DateField(default=datetime.date(2024, 5, 4)),
        ),
    ]
