# Generated by Django 4.2.4 on 2024-05-05 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0010_alter_usuarioegresos_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioegresos',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='usuarioingresos',
            name='fecha',
        ),
    ]
