# Generated by Django 4.2.4 on 2024-05-05 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0012_remove_crecimientoempresa_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='crecimientoempresa',
            name='fecha',
            field=models.DateField(default=datetime.date(2024, 5, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarioegresos',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 4), null=True),
        ),
        migrations.AddField(
            model_name='usuarioingresos',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 4), null=True),
        ),
    ]
