# Generated by Django 4.2.4 on 2024-05-05 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0013_crecimientoempresa_fecha_usuarioegresos_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crecimientoempresa',
            name='fecha',
            field=models.DateField(default=datetime.date(2024, 5, 4)),
        ),
        migrations.AlterField(
            model_name='usuarioegresos',
            name='fecha',
            field=models.DateField(default=datetime.date(2024, 5, 4)),
        ),
        migrations.AlterField(
            model_name='usuarioingresos',
            name='fecha',
            field=models.DateField(default=datetime.date(2024, 5, 4)),
        ),
    ]
