# Generated by Django 4.2.4 on 2024-05-05 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0015_alter_crecimientoempresa_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crecimientoempresa',
            name='crecimiento',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='UsuarioResumenInversiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.CharField(max_length=500)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invertidoR', to='UserData.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioResumenIngresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.CharField(max_length=500)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresadoR', to='UserData.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioResumenEgresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen', models.CharField(max_length=500)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresadoR', to='UserData.usuario')),
            ],
        ),
    ]
